baseURL = "https://pawelsawicz.github.io/oufc-website3"
languageCode = "en-us"
title = "OUFC"
themesDir = "themes"
theme = "ananke"
publishDir = "docs"
pcc_logo = "/images/logo.png"
custom_css = ["css/custom.css"]
enableRobotsTXT = true

[params]
    facebook = "https://www.facebook.com/PolishCityClub/"
    twitter = "https://twitter.com/PolishCityClub"
    linkedin = "https://www.linkedin.com/company/polish-city-club"
    featured_image = "/images/fencing.jpg"

[menu]

    [[menu.main]]
        name = "About"
        weight = -45
        identifier = "about"
        url = "/about/"
